### ISSUE TITLE
Could I change the default url of dashboard

### ISSUE THREAD

**Issue by yichengchen** [alexazhou/VeryNginx#27]
Although I can use rewrite rule to make a shorten url,But how can I block access from the original /verynginx/dashboard/ ?

**Comment by alexazhou** [comment]
Because rewrite is run before the filter, so you can't simple block /verynginx/dashboard

One way is that rewrite /verynginx/dashboard/... to other uri like '/notallow', and use filter to block all request to /notallow

**Comment by yichengchen** [comment]
Could you explain a little more detailed? I'm not familiar with rewrite rules.

I had try  several times but failed. I set up a rewrite with a matcher of 'verynginx' and blank RegEx,Redirect to /noallow. After I set up this.both access from /vn/index.html and /verynginx/dashboard/... return 404. What should I do?

**Comment by alexazhou** [comment]
Oh, I'm sorry . 
I had try that myself and fount it's impossible to change original dashboard uri to other at now.

The reason is the uri  `/verynginx/...` was written in some source code fixed.So that no matter what  uri the dashboard use, javascript will use the original address (/verynginx/...) to initiate ajax request. Because of that we can't block the original address

I will fixed that in a few days😑

**Comment by alexazhou** [comment]
Fixed in adbf77d

Some problem was fixed and the entry of control panel has changed to `/verynginx/index.html`
please pull the code and clean config.json.

You can do as the following steps :

1，Use rewrite action to make a short replacement for '/verynginx/index.html'. Actually there default config already do that. Is /vn/index.html. So you need do nothing but understand how it works.

2，Add a matcher that has a condition uri match the Regex '^/verynginx'. And make a rewrite rule  refer the matcher , with  blank RegEx, Rewrite to /notallow. 

3，Add a matcher that has a condition uri equal '/notallow'. And make a filter rule  refer the matcher , with action block, status code 403.

**Comment by yichengchen** [comment]
Thanks it works !
