### ISSUE TITLE
是否可以将安装脚本换成shell脚本，现在需要多依赖一个python了

### ISSUE THREAD

**Issue by halfcrazy** [alexazhou/VeryNginx#39]

**Comment by alexazhou** [comment]
其实原理上是可以的，这里用了 python 实现安装脚本，是因为python更灵活，还有 shell 脚本比较麻烦

话说一般发行版本都自带了python吧，依赖 python 并不会有什么影响吧？

**Comment by cobola** [comment]
configure: error: the HTTP rewrite module requires the PCRE library.
You can either disable the module by using --without-http_rewrite_module
option, or install the PCRE library into the system, or build the PCRE library
statically from the source with nginx by using --with-pcre=<path> option.

ERROR: failed to run command: sh ./configure --prefix=/opt/verynginx/openresty/nginx \...
*** The installing stopped because something was wrong 

比较弱... 就按照 python install.py install 报错 啥情况？

**Comment by alexazhou** [comment]
缺少了 PCRE 库的头文件，所以编译的时候出错了
把头文件安装上就好啦

参考我在中的回答： http://www.v2ex.com/t/275763#reply40

**Comment by cobola** [comment]
恩 看到了 ubuntu 下安装 sudo apt-get install libpcre3 libpcre3-dev  

另外 我看你脚本里面写的 写死了 /opt/verynginx 路径是么？ 正在编译中

**Comment by alexazhou** [comment]
对的，因为一些原因，目前只能安装到 /opt/verynginx 这个目录下面
