### ISSUE TITLE
openresty编译安装过程中退出

### ISSUE THREAD

**Issue by la0wei** [alexazhou/VeryNginx#52]
make[2]: Leaving directory '/root/openresty-1.9.7.5/build/nginx-1.9.7'
make[1]: Leaving directory '/root/openresty-1.9.7.5/build/nginx-1.9.7'
### copy VeryNginx files ...
cp -r -f ./verynginx /opt/verynginx
cp: cannot stat './verynginx': No such file or directory
*** The installing stopped because something was wrong
安装到这步还能用吗？

**Comment by alexazhou** [comment]
需要cd到代码仓库目录下执行安装命令。


从日志来看安装没完成，应该不能用







发自网易邮箱 iPhone 版
在2016年06月03日 00:35，la0wei 写道:

make[2]: Leaving directory '/root/openresty-1.9.7.5/build/nginx-1.9.7'
make[1]: Leaving directory '/root/openresty-1.9.7.5/build/nginx-1.9.7'

copy VeryNginx files ...

cp -r -f ./verynginx /opt/verynginx
cp: cannot stat './verynginx': No such file or directory
*** The installing stopped because something was wrong
安装到这步还能用吗？

**Comment by la0wei** [comment]
我单独下载了verynginx的install.py，同时安装了openresty依赖。看起来编译已经完成了，只是配置文件可能缺失，所以出现另一个issue中的404问题

**Comment by alexazhou** [comment]
后续回复在 #51 中
